### ISSUE TITLE
Subsequent Labs use ActiveRecord 5.2, example needs updating.

### ISSUE THREAD

**Issue by dstoll243** [learn-co-curriculum/active-record-writing-migrations-lab#1]
Example at the bottom of the reading shows specifying the ActiveRecord version as 4.2. However, subsequent labs are now using 5.2, which can lead to confusion.

**Comment by maxwellbenton** [comment]
Thanks @dahby for catching this and providing the fix. I've merged in the PR so this should be consistent now.
